import Head from "next/head";
import Image from "next/image";
import { useSelector } from "react-redux";
import Do from "../components/Do";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Offer from "../components/Offer";
import Pic from "../components/Pic";
import { selectHamburger } from "../redux/slices/hamburger";
import styles from "../styles/Home.module.css";

export default function Home() {
  const bool = useSelector(selectHamburger);
  console.log(bool);

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="home" className="bg-[#0A1931] text-white">
        <Navbar />
        <div className="home">
          <div className="overview pt-36 grid md:grid-cols-2 gap-4">
            <div className="flex justify-evenly md:justify-end cursor-pointer">
              <Pic />
            </div>
            <div className="flex md:justify-start items-center md:items-start flex-col text-left px-10">
              <p className="my-3 text-sm text-gray-400">React-developer</p>
              <h1 className="my-3 text-xl tracking-widest">Musa Malik</h1>
              <p className="my-5 text-sm text-gray-300">
                Welcome to my personal portfolio web. My name is Musa and I am a
                passionate developer. I am working as a freelancer. I give
                myself a mission to produce creative websites and applications
                with beautifull details. I enrich the design with my own
                illustrations and designs that are created with precision and
                based on your desire.
              </p>
              {/* <button className="btn" onClick={)}>
                        </button> */}
              <button className="text-left text-sm mt-8 w-20 pl-3 pb-2 rounded-2xl p-2 border-2 border-[#00C1D4]">
                Contact
              </button>
            </div>
          </div>
          <div className="what-i-do m-10">
            <h3 className="hr text-2xl font-semibold tracking-wider">
              What I Do
            </h3>
            <hr className="bg-[#00C1D4] w-10 mt-2 h-0.5 outline-none border-none rounded-full" />
            <Do />
          </div>
          <div className="what-i-offer m-10 mb-0">
            <h3 className="hr text-2xl font-semibold tracking-wider">
              What I Offer
            </h3>
            <hr className="bg-[#00C1D4] w-10 mt-2 h-0.5 outline-none border-none rounded-full" />
            <Offer />
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}
